language: node_js
node_js:
  - lts/*
  - node
env:
  - FRONTEND_URL: https://api.parkettklub.sch.bme.hu/

script:
  - yarn build --prefix-paths

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
